version: '3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_USER: food_delivery
      MYSQL_PASSWORD: 1111
      MYSQL_DATABASE: food_delivery
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"

  myapp:
    # image: zongji-app
    build: ./app
    restart: always
    depends_on:
      - mysql

